use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));

    generate_red_words_glsl(&manifest_dir, &out_dir);

    compile_shader(&manifest_dir, &out_dir, "packet_prefilter.comp");
    compile_shader(&manifest_dir, &out_dir, "audit_prefilter.comp");
}

fn generate_red_words_glsl(_manifest_dir: &Path, out_dir: &Path) {
    // KAIRO-FW: Static red words (Ethics-free, technical focus only)
    let tech_words = vec!["eval(".to_string(), "Direct Syscalls".to_string()];
    let harm_words: Vec<String> = vec![];
    let conceal_words: Vec<String> = vec![];

    let mut glsl = String::new();
    glsl.push_str("// Generated by build.rs for KAIRO-FW - DO NOT EDIT\n\n");

    write_glsl_array(&mut glsl, "TECH", &tech_words);
    write_glsl_array(&mut glsl, "HARM", &harm_words);
    write_glsl_array(&mut glsl, "CONCEAL", &conceal_words);

    fs::write(out_dir.join("red_words.glsl"), glsl).expect("write red_words.glsl");
}

fn write_glsl_array(glsl: &mut String, category: &str, words: &[String]) {
    glsl.push_str(&format!(
        "const uint {}_WORD_COUNT = {}u;\n",
        category,
        words.len()
    ));

    let mut packed_data = Vec::new();
    let mut offsets = Vec::new();
    let mut lengths = Vec::new();

    let mut current_offset = 0;
    for word in words {
        offsets.push(current_offset);
        lengths.push(word.len());
        let bytes = word.as_bytes();
        for chunk in bytes.chunks(4) {
            let mut val = 0u32;
            for (i, &b) in chunk.iter().enumerate() {
                val |= (b as u32) << (i * 8);
            }
            packed_data.push(val);
        }
        current_offset += (word.len() + 3) / 4;
    }

    glsl.push_str(&format!(
        "const uint {}_PACKED_SIZE = {}u;\n",
        category,
        packed_data.len()
    ));
    
    if packed_data.is_empty() {
        glsl.push_str(&format!("const uint {}_WORDS_PACKED[1] = uint[](0u);\n", category));
        glsl.push_str(&format!("const uint {}_OFFSETS[1] = uint[](0u);\n", category));
        glsl.push_str(&format!("const uint {}_LENGTHS[1] = uint[](0u);\n\n", category));
    } else {
        glsl.push_str(&format!("const uint {}_WORDS_PACKED[] = uint[](", category));
        for (i, val) in packed_data.iter().enumerate() {
            if i > 0 { glsl.push_str(", "); }
            glsl.push_str(&format!("0x{:08x}u", val));
        }
        glsl.push_str(");\n");

        glsl.push_str(&format!("const uint {}_OFFSETS[] = uint[](", category));
        for (i, val) in offsets.iter().enumerate() {
            if i > 0 { glsl.push_str(", "); }
            glsl.push_str(&format!("{}u", val));
        }
        glsl.push_str(");\n");

        glsl.push_str(&format!("const uint {}_LENGTHS[] = uint[](", category));
        for (i, val) in lengths.iter().enumerate() {
            if i > 0 { glsl.push_str(", "); }
            glsl.push_str(&format!("{}u", val));
        }
        glsl.push_str(");\n\n");
    }
}

fn compile_shader(manifest_dir: &Path, out_dir: &Path, shader_name: &str) {
    let shader_path = manifest_dir.join("shaders").join(shader_name);
    println!("cargo:rerun-if-changed={}", shader_path.display());

    let mut source = fs::read_to_string(&shader_path).expect("read shader");

    if source.contains("#include \"red_words.glsl\"") {
        let include_content = fs::read_to_string(out_dir.join("red_words.glsl")).expect("read glsl");
        source = source.replace("#include \"red_words.glsl\"", &include_content);
    }

    let compiler = shaderc::Compiler::new().expect("shaderc compiler");
    let mut options = shaderc::CompileOptions::new().expect("shaderc options");
    options.set_target_env(shaderc::TargetEnv::Vulkan, shaderc::EnvVersion::Vulkan1_0 as u32);
    options.set_optimization_level(shaderc::OptimizationLevel::Performance);

    let artifact = compiler.compile_into_spirv(
        &source,
        shaderc::ShaderKind::Compute,
        shader_path.to_string_lossy().as_ref(),
        "main",
        Some(&options)
    ).expect("compile error");

    fs::write(out_dir.join(format!("{}.spv", shader_name)), artifact.as_binary_u8()).expect("write error");
}
